### ISSUE TITLE
Decode From Protein Representation

### ISSUE THREAD

**Issue by Leo-T-Zang** [agemagician/Ankh#27]
Hi,

Thanks for this amazing work.

I am wondering if AnKh supports decoding from extracted protein representation.

Thank you!

**Comment by pjspol** [comment]
I was also wondering if this is possible.

**Comment by hazemessamm** [comment]
Yes, it supports decoding from extracted protein representation, check out this notebook https://github.com/agemagician/Ankh/blob/main/examples/simple_generation.ipynb.

When you initialize the model pass `generation=True` (e.g. `ankh.load_ankh_base(generation=True)`), It will return T5ForConditionalGeneration that will contain the encoder and the decoder that you can use for decoding the extracted protein representation.

Sorry for the late response. I will keep this issue open in case I did not answer your question.

**Comment by Leo-T-Zang** [comment]
Thank you so much for your reply!

**Comment by Zebreu** [comment]
@hazemessamm I read the generation notebook, but I'm not sure how to pass it a 768-wide tensor (the encoder's hidden state, essentially) to the decoder so I get a list of tokens as a result. Is this possible?
