### ISSUE TITLE
Secondary structure prediction dataset

### ISSUE THREAD

**Issue by aalksii** [agemagician/Ankh#33]
Hi!

When running examples/secondary_structure_prediction_3_states.ipynb, I have an error with downloading dataset from HuggingFace. It looks like there are no such files as stated in the script.

> FileNotFoundError: Couldn't find a dataset script at /home/u/Ankh/examples/proteinea/SSP/SSP.py or any data file in the same directory. Couldn't find 'proteinea/SSP' on the Hugging Face Hub either: FileNotFoundError: Unable to find training_data.csv in dataset repository proteinea/secondary_structure_prediction with any supported extension ['csv', ...]

Also, is there a straightforward way to use Ankh for secondary structure prediction on a single sequence protein?

**Comment by hazemessamm** [comment]
Will fix it, we just changed the dataset names for more clarity. Regarding the second question I think I don't understand it, could you please clarify what you mean by a single sequence protein? Do you mean like providing a trained model that you can just pass to it a single sequence?
