### ISSUE TITLE
How to compute the perplexity of a protein sequence by ankh PLM? 

### ISSUE THREAD

**Issue by liusfore** [agemagician/Ankh#35]

**Comment by hazemessamm** [comment]
Hello, sorry for the late reply.

If you are using PyTorch, you can install `torcheval` using `pip install torcheval`  then use the `Perplexity` class to compute the perplexity for you, for more information check out: https://pytorch.org/torcheval/main/generated/torcheval.metrics.Perplexity.html

If you are using Keras, you can use KerasNLP library that has different metrics functions, to use Perplexity from KerasNLP: `keras_nlp.metrics.Perplexity()` and for more information check out: https://keras.io/api/keras_nlp/metrics/perplexity/
