### ISSUE TITLE
Generation within Sequence/Mask prediction

### ISSUE THREAD

**Issue by johnsantamariajr** [agemagician/Ankh#38]
Thank you authors for your publication and work in open sourcing :)
Was able to run the simple_generation example you provided - this is great if one wants to generate at the end of a sequence.
Is it possible to generate within the middle of a sequence, using the existing model and mask token as well?

**Comment by lhallee** [comment]
I also have this question! Have not been able to get this working.

**Comment by johnsantamariajr** [comment]
I realize the authors have indeed provided this in their example, but that the notebook's output printing is written to always append at the end. Standard generation works with the following snippet:


```python
masked_seq='QVQLVESGGGLV<extra_id_0>QPGGSL'
encoded = tokenizer.encode_plus(masked_seq, add_special_tokens=True, return_tensors='pt') 
input_ids = encoded['input_ids'].to(device)
generation = model.generate(input_ids=input_ids, temperature = temperature,
                                max_length = maximum_length,
                                num_beams = num_beams,
                                do_sample=True if temperature > 0 else False)
output_ids = generation[0].squeeze()
generated_tokens = list(tokenizer.decode(output_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False))
``` 
I will close this issue. Thanks!

**Comment by lhallee** [comment]
I noticed this too, outputs in the order that you masked them. Best of luck with everything!
